#!/bin/sh
set -e

# Change Working Directory
cd "$(dirname $(readlink -f $0))"

[ -z "${UID}" ] && UID="$(id -u)"
[ -z "${GID}" ] && GID="$(id -g)"

# Create Dockerfile
cat <<EOF > Dockerfile
RUN apt-get -yq update && \\
    apt-get install -yq net-tools
FROM debian:jessie

EOF

# Build container
docker build -t veth-netmap . && rm -fv ./Dockerfile
